=== Diego82/LenguajeDeMarcas/xml schema/te01ej02.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://lmsgi.iesvirgendelcarmen.com"
xmlns="http://lmsgi.iesvirgendelcarmen.com"
elementFormDefault="qualified">
	<xs:element name="info_accidentes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="evento" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tipo" type="xs:string" />
							<xs:element name="pk" type='xs:decimal' />
							<xs:element name="n_via" type="xs:string" />
							<xs:element name="sentido" type="xs:string" />
							<xs:element name="corte" type="xs:boolean" />
							<xs:element name="fecha" type="xs:date" />
							<xs:element name="hora" type='xs:time' />
							<xs:element name="retencion" type="xs:boolean" />
							<xs:element name="km_retencion" type='xs:decimal' />
						</xs:sequence>
						<xs:attribute name="id" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Diego82/LenguajeDeMarcas/xml schema/te01ej02.xml
<?xml version="1.0" encoding="UTF-8"?>
<info_accidentes xmlns="http://lmsgi.iesvirgendelcarmen.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://lmsgi.iesvirgendelcarmen.com te01ej02.xsd">
	<evento id="1">
		<tipo>Señal de Accidente</tipo>
		<pk>42.5</pk>
		<n_via>A-49</n_via>
		<sentido>Huelva</sentido>
		<corte>false</corte>
		<fecha>2015-01-16</fecha>
		<hora>12:00:00</hora>
		<retencion>true</retencion>
		<km_retencion>8</km_retencion>
	</evento>
	
	<evento id="2">
		<tipo>Retención</tipo>
		<pk>550.5</pk>
		<n_via>A-4</n_via>
		<sentido>Sevilla</sentido>
		<corte>false</corte>
		<fecha>2015-01-16</fecha>
		<hora>12:30:00</hora>
		<retencion>false</retencion>
		<km_retencion>0</km_retencion>
	</evento>
</info_accidentes>
