=== Diego82/LenguajeDeMarcas/xml schema/te01ej04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://lmsgi.iesvirgendelcarmen.com"
xmlns="http://lmsgi.iesvirgendelcarmen.com" 
elementFormDefault="qualified">
<xs:element name="factura">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="cliente">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="dni" type="xs:string" />
						<xs:element name="nombre" type="xs:string" />
						<xs:element name="direccion" type="xs:string"  />
						<xs:element name="cp" type="xs:integer"  />
						<xs:element name="poblacion" type="xs:string"  />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="pedido">
				<xs:complexType>
					<xs:sequence>
						
						<xs:element name="producto" minOccurs="1" maxOccurs="unbounded" >
							<xs:complexType>
								
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="precio" type="xs:double" use="required" />
									<xs:attribute name="nombre" type="xs:string" use="required" />
									<xs:attribute name="iva" type="xs:double" use="required" />
									<xs:attribute name="desc" type="xs:double" use="required" />
									<xs:attribute name="cantidad" type="xs:integer" use="required" />
							
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Diego82/LenguajeDeMarcas/xml schema/te01ej04.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns="http://lmsgi.iesvirgendelcarmen.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://lmsgi.iesvirgendelcarmen.com te01ej04.xsd">
	<cliente>
		<dni>77332216Y</dni>
		<nombre>Diego Torres</nombre>
		<direccion>Av Andalucia</direccion>
		<cp>23005</cp>
		<poblacion>Ja√©n</poblacion>
	</cliente>

	<pedido>
		<producto id="92332" precio="50" nombre="Disco duro HDD" iva="21" desc="3" cantidad="4" />
		<producto id="23332" precio="80" nombre="Disco duro SSD" iva="21" desc="3" cantidad="4" />
	</pedido>

</factura>
